CREATE TABLE [dbo].[ComposicoesAcionarias] (
    [Id]                                    UNIQUEIDENTIFIER NOT NULL,
    [EmpresaId]                             INT              NOT NULL,
    [PessoaTipo]                            SMALLINT         NOT NULL,
    [SocioTipo]                             SMALLINT         NOT NULL,
    [Cep]                                   VARCHAR (15)     NULL,
    [Logradouro]                            VARCHAR (200)    NOT NULL,
    [Numero]                                VARCHAR (10)     NOT NULL,
    [Complemento]                           VARCHAR (80)     NULL,
    [Bairro]                                VARCHAR (100)    NULL,
    [Cidade]                                VARCHAR (100)    NOT NULL,
    [Estado]                                VARCHAR (5)      NULL,
    [CaixaPostal]                           VARCHAR (10)     NULL,
    [PorcentagemCapitalVolante]             DECIMAL (5, 2)   NOT NULL,
    [PorcentagemCapitalTotal]               DECIMAL (5, 2)   NOT NULL,
    [Nome]                                  VARCHAR (15)     NULL,
    [Sobrenome]                             VARCHAR (200)    NULL,
    [Cpf]                                   VARCHAR (11)     NULL,
    [Genero]                                SMALLINT         NOT NULL,
    [Passaporte]                            VARCHAR (15)     NULL,
    [TaxIdentificationNumber]               VARCHAR (15)     NULL,
    [OutrosIdentificacaoTipo]               VARCHAR (100)    NULL,
    [OutrosIdentificacaoNumero]             VARCHAR (15)     NULL,
    [DataNascimento]                        DATETIME2 (7)    NOT NULL,
    [Nacionalidade]                         VARCHAR (100)    NULL,
    [Naturalidade]                          VARCHAR (100)    NULL,
    [ResidenciaFiscal]                      VARCHAR (150)    NULL,
    [PertenceQuadroAdministrativoDiretoria] VARCHAR (100)    NOT NULL,
    [DiretoriaCargo]                        VARCHAR (100)    NULL,
    [DiretoriaDataEntrada]                  DATETIME2 (7)    NULL,
    [DiretoriaDataSaida]                    DATETIME2 (7)    NULL,
    [PertenceConselhoAdministracao]         VARCHAR (100)    NOT NULL,
    [AdministracaoCargo]                    VARCHAR (100)    NULL,
    [AdministracaoDataEntrada]              DATETIME2 (7)    NULL,
    [AdministracaoDataSaida]                DATETIME2 (7)    NULL,
    [NumeroIdentificacao]                   VARCHAR (30)     NULL,
    [NomeEmpresa]                           VARCHAR (300)    NULL,
    [ComprovanteIdentidade]                 BIT              NOT NULL,
    [ComprovanteResidencia]                 BIT              NOT NULL,
    [CertidaoCasamento]                     BIT              NOT NULL,
    [Outros]                                BIT              NOT NULL,
    [CartaoAssinatura]                      BIT              NOT NULL,
    [Cnpj]                                  BIT              NOT NULL,
    [DataCriacao]                           DATETIME2 (7)    NULL,
    [UsuarioCriacaoId]                      INT              NULL,
    [DataAlteracao]                         DATETIME2 (7)    NULL,
    [UsuarioAlteracaoId]                    INT              NULL,
    [NomeArquivo]                           VARCHAR (200)    NULL,
    [PaisId]                                INT              DEFAULT ((0)) NOT NULL,
    CONSTRAINT [PK_ComposicoesAcionarias] PRIMARY KEY CLUSTERED ([Id] ASC)
);

