CREATE TABLE [dbo].[RepresentantesLegais] (
    [Id]                        UNIQUEIDENTIFIER NOT NULL,
    [EmpresaId]                 INT              NOT NULL,
    [Nome]                      VARCHAR (100)    NOT NULL,
    [Sobrenome]                 VARCHAR (200)    NOT NULL,
    [Situacao]                  INT              NOT NULL,
    [Cpf]                       VARCHAR (11)     NULL,
    [Passaporte]                VARCHAR (15)     NULL,
    [TaxIdentificationNumber]   VARCHAR (15)     NULL,
    [OutrosIdentificacaoTipo]   VARCHAR (100)    NULL,
    [OutrosIdentificacaoNumero] VARCHAR (15)     NULL,
    [Genero]                    SMALLINT         NOT NULL,
    [DataNascimento]            DATETIME2 (7)    NOT NULL,
    [Nacionalidade]             VARCHAR (100)    NULL,
    [Naturalidade]              VARCHAR (100)    NULL,
    [Profissao]                 VARCHAR (300)    NULL,
    [EstadoCivil]               SMALLINT         NOT NULL,
    [Cep]                       VARCHAR (15)     NULL,
    [Logradouro]                VARCHAR (200)    NOT NULL,
    [Numero]                    VARCHAR (10)     NULL,
    [Complemento]               VARCHAR (80)     NULL,
    [Bairro]                    VARCHAR (100)    NULL,
    [Cidade]                    VARCHAR (100)    NOT NULL,
    [Estado]                    VARCHAR (5)      NULL,
    [Cargo]                     VARCHAR (200)    NULL,
    [DataInicioAtividades]      DATETIME2 (7)    NULL,
    [ComprovanteIdentidade]     BIT              NOT NULL,
    [ComprovanteResidencia]     BIT              NOT NULL,
    [CertidaoCasamento]         BIT              NOT NULL,
    [Outros]                    BIT              NOT NULL,
    [CartaoAssinatura]          BIT              NOT NULL,
    [DataCriacao]               DATETIME2 (7)    NULL,
    [UsuarioCriacaoId]          INT              NULL,
    [DataAlteracao]             DATETIME2 (7)    NULL,
    [UsuarioAlteracaoId]        INT              NULL,
    [PaisId]                    INT              DEFAULT ((0)) NOT NULL,
    CONSTRAINT [PK_RepresentantesLegais] PRIMARY KEY CLUSTERED ([Id] ASC)
);



